package net.nemezanevem.gregtech.api.unification.material;

import net.minecraftforge.registries.RegistryObject;

import java.util.HashMap;
import java.util.Map;

import static net.nemezanevem.gregtech.api.registry.material.ElementRegistry.ELEMENTS;

public class GtElements {

    public static final RegistryObject<Element> H = ELEMENTS.register("hydrogen", () -> new Element(1, 0, -1, null, "H", false));
    public static final RegistryObject<Element> D = ELEMENTS.register("Deuterium", () -> new Element(1, 1, -1, "H", "D", true));
    public static final RegistryObject<Element> T = ELEMENTS.register("Tritium", () -> new Element(1, 2, -1, "D", "T", true));
    public static final RegistryObject<Element> He = ELEMENTS.register("Helium", () -> new Element(2, 2, -1, null, "He", false));
    public static final RegistryObject<Element> He3 = ELEMENTS.register("Helium-3", () -> new Element(2, 1, -1, "H&D", "He-3", true));
    public static final RegistryObject<Element> Li = ELEMENTS.register("Lithium", () -> new Element(3, 4, -1, null, "Li", false));
    public static final RegistryObject<Element> Be = ELEMENTS.register("Beryllium", () -> new Element(4, 5, -1, null, "Be", false));
    public static final RegistryObject<Element> B = ELEMENTS.register("Boron", () -> new Element(5, 5, -1, null, "B", false));
    public static final RegistryObject<Element> C = ELEMENTS.register("Carbon", () -> new Element(6, 6, -1, null, "C", false));
    public static final RegistryObject<Element> N = ELEMENTS.register("Nitrogen", () -> new Element(7, 7, -1, null, "N", false));
    public static final RegistryObject<Element> O = ELEMENTS.register("Oxygen", () -> new Element(8, 8, -1, null, "O", false));
    public static final RegistryObject<Element> F = ELEMENTS.register("Fluorine", () -> new Element(9, 9, -1, null, "F", false));
    public static final RegistryObject<Element> Ne = ELEMENTS.register("Neon", () -> new Element(10, 10, -1, null, "Ne", false));
    public static final RegistryObject<Element> Na = ELEMENTS.register("Sodium", () -> new Element(11, 11, -1, null, "Na", false));
    public static final RegistryObject<Element> Mg = ELEMENTS.register("Magnesium", () -> new Element(12, 12, -1, null, "Mg", false));
    public static final RegistryObject<Element> Al = ELEMENTS.register("Aluminium", () -> new Element(13, 13, -1, null, "Al", false));
    public static final RegistryObject<Element> Si = ELEMENTS.register("Silicon", () -> new Element(14, 14, -1, null, "Si", false));
    public static final RegistryObject<Element> P = ELEMENTS.register("Phosphorus", () -> new Element(15, 15, -1, null, "P", false));
    public static final RegistryObject<Element> S = ELEMENTS.register("Sulfur", () -> new Element(16, 16, -1, null, "S", false));
    public static final RegistryObject<Element> Cl = ELEMENTS.register("Chlorine", () -> new Element(17, 18, -1, null, "Cl", false));
    public static final RegistryObject<Element> Ar = ELEMENTS.register("Argon", () -> new Element(18, 22, -1, null, "Ar", false));
    public static final RegistryObject<Element> K = ELEMENTS.register("Potassium", () -> new Element(19, 20, -1, null, "K", false));
    public static final RegistryObject<Element> Ca = ELEMENTS.register("Calcium", () -> new Element(20, 20, -1, null, "Ca", false));
    public static final RegistryObject<Element> Sc = ELEMENTS.register("Scandium", () -> new Element(21, 24, -1, null, "Sc", false));
    public static final RegistryObject<Element> Ti = ELEMENTS.register("Titanium", () -> new Element(22, 26, -1, null, "Ti", false));
    public static final RegistryObject<Element> V = ELEMENTS.register("Vanadium", () -> new Element(23, 28, -1, null, "V", false));
    public static final RegistryObject<Element> Cr = ELEMENTS.register("Chrome", () -> new Element(24, 28, -1, null, "Cr", false));
    public static final RegistryObject<Element> Mn = ELEMENTS.register("Manganese", () -> new Element(25, 30, -1, null, "Mn", false));
    public static final RegistryObject<Element> Fe = ELEMENTS.register("Iron", () -> new Element(26, 30, -1, null, "Fe", false));
    public static final RegistryObject<Element> Co = ELEMENTS.register("Cobalt", () -> new Element(27, 32, -1, null, "Co", false));
    public static final RegistryObject<Element> Ni = ELEMENTS.register("Nickel", () -> new Element(28, 30, -1, null, "Ni", false));
    public static final RegistryObject<Element> Cu = ELEMENTS.register("Copper", () -> new Element(29, 34, -1, null, "Cu", false));
    public static final RegistryObject<Element> Zn = ELEMENTS.register("Zinc", () -> new Element(30, 35, -1, null, "Zn", false));
    public static final RegistryObject<Element> Ga = ELEMENTS.register("Gallium", () -> new Element(31, 39, -1, null, "Ga", false));
    public static final RegistryObject<Element> Ge = ELEMENTS.register("Germanium", () -> new Element(32, 40, -1, null, "Ge", false));
    public static final RegistryObject<Element> As = ELEMENTS.register("Arsenic", () -> new Element(33, 42, -1, null, "As", false));
    public static final RegistryObject<Element> Se = ELEMENTS.register("Selenium", () -> new Element(34, 45, -1, null, "Se", false));
    public static final RegistryObject<Element> Br = ELEMENTS.register("Bromine", () -> new Element(35, 45, -1, null, "Br", false));
    public static final RegistryObject<Element> Kr = ELEMENTS.register("Krypton", () -> new Element(36, 48, -1, null, "Kr", false));
    public static final RegistryObject<Element> Rb = ELEMENTS.register("Rubidium", () -> new Element(37, 48, -1, null, "Rb", false));
    public static final RegistryObject<Element> Sr = ELEMENTS.register("Strontium", () -> new Element(38, 49, -1, null, "Sr", false));
    public static final RegistryObject<Element> Y = ELEMENTS.register("Yttrium", () -> new Element(39, 50, -1, null, "Y", false));
    public static final RegistryObject<Element> Zr = ELEMENTS.register("Zirconium", () -> new Element(40, 51, -1, null, "Zr", false));
    public static final RegistryObject<Element> Nb = ELEMENTS.register("Niobium", () -> new Element(41, 53, -1, null, "Nb", false));
    public static final RegistryObject<Element> Mo = ELEMENTS.register("Molybdenum", () -> new Element(42, 53, -1, null, "Mo", false));
    public static final RegistryObject<Element> Tc = ELEMENTS.register("Technetium", () -> new Element(43, 55, -1, null, "Tc", false));
    public static final RegistryObject<Element> Ru = ELEMENTS.register("Ruthenium", () -> new Element(44, 57, -1, null, "Ru", false));
    public static final RegistryObject<Element> Rh = ELEMENTS.register("Rhodium", () -> new Element(45, 58, -1, null, "Rh", false));
    public static final RegistryObject<Element> Pd = ELEMENTS.register("Palladium", () -> new Element(46, 60, -1, null, "Pd", false));
    public static final RegistryObject<Element> Ag = ELEMENTS.register("Silver", () -> new Element(47, 60, -1, null, "Ag", false));
    public static final RegistryObject<Element> Cd = ELEMENTS.register("Cadmium", () -> new Element(48, 64, -1, null, "Cd", false));
    public static final RegistryObject<Element> In = ELEMENTS.register("Indium", () -> new Element(49, 65, -1, null, "In", false));
    public static final RegistryObject<Element> Sn = ELEMENTS.register("Tin", () -> new Element(50, 68, -1, null, "Sn", false));
    public static final RegistryObject<Element> Sb = ELEMENTS.register("Antimony", () -> new Element(51, 70, -1, null, "Sb", false));
    public static final RegistryObject<Element> Te = ELEMENTS.register("Tellurium", () -> new Element(52, 75, -1, null, "Te", false));
    public static final RegistryObject<Element> I = ELEMENTS.register("Iodine", () -> new Element(53, 74, -1, null, "I", false));
    public static final RegistryObject<Element> Xe = ELEMENTS.register("Xenon", () -> new Element(54, 77, -1, null, "Xe", false));
    public static final RegistryObject<Element> Cs = ELEMENTS.register("Caesium", () -> new Element(55, 77, -1, null, "Cs", false));
    public static final RegistryObject<Element> Ba = ELEMENTS.register("Barium", () -> new Element(56, 81, -1, null, "Ba", false));
    public static final RegistryObject<Element> La = ELEMENTS.register("Lanthanum", () -> new Element(57, 81, -1, null, "La", false));
    public static final RegistryObject<Element> Ce = ELEMENTS.register("Cerium", () -> new Element(58, 82, -1, null, "Ce", false));
    public static final RegistryObject<Element> Pr = ELEMENTS.register("Praseodymium", () -> new Element(59, 81, -1, null, "Pr", false));
    public static final RegistryObject<Element> Nd = ELEMENTS.register("Neodymium", () -> new Element(60, 84, -1, null, "Nd", false));
    public static final RegistryObject<Element> Pm = ELEMENTS.register("Promethium", () -> new Element(61, 83, -1, null, "Pm", false));
    public static final RegistryObject<Element> Sm = ELEMENTS.register("Samarium", () -> new Element(62, 88, -1, null, "Sm", false));
    public static final RegistryObject<Element> Eu = ELEMENTS.register("Europium", () -> new Element(63, 88, -1, null, "Eu", false));
    public static final RegistryObject<Element> Gd = ELEMENTS.register("Gadolinium", () -> new Element(64, 93, -1, null, "Gd", false));
    public static final RegistryObject<Element> Tb = ELEMENTS.register("Terbium", () -> new Element(65, 93, -1, null, "Tb", false));
    public static final RegistryObject<Element> Dy = ELEMENTS.register("Dysprosium", () -> new Element(66, 96, -1, null, "Dy", false));
    public static final RegistryObject<Element> Ho = ELEMENTS.register("Holmium", () -> new Element(67, 97, -1, null, "Ho", false));
    public static final RegistryObject<Element> Er = ELEMENTS.register("Erbium", () -> new Element(68, 99, -1, null, "Er", false));
    public static final RegistryObject<Element> Tm = ELEMENTS.register("Thulium", () -> new Element(69, 99, -1, null, "Tm", false));
    public static final RegistryObject<Element> Yb = ELEMENTS.register("Ytterbium", () -> new Element(70, 103, -1, null, "Yb", false));
    public static final RegistryObject<Element> Lu = ELEMENTS.register("Lutetium", () -> new Element(71, 103, -1, null, "Lu", false));
    public static final RegistryObject<Element> Hf = ELEMENTS.register("Hafnium", () -> new Element(72, 106, -1, null, "Hf", false));
    public static final RegistryObject<Element> Ta = ELEMENTS.register("Tantalum", () -> new Element(73, 107, -1, null, "Ta", false));
    public static final RegistryObject<Element> W = ELEMENTS.register("Tungsten", () -> new Element(74, 109, -1, null, "W", false));
    public static final RegistryObject<Element> Re = ELEMENTS.register("Rhenium", () -> new Element(75, 111, -1, null, "Re", false));
    public static final RegistryObject<Element> Os = ELEMENTS.register("Osmium", () -> new Element(76, 114, -1, null, "Os", false));
    public static final RegistryObject<Element> Ir = ELEMENTS.register("Iridium", () -> new Element(77, 115, -1, null, "Ir", false));
    public static final RegistryObject<Element> Pt = ELEMENTS.register("Platinum", () -> new Element(78, 117, -1, null, "Pt", false));
    public static final RegistryObject<Element> Au = ELEMENTS.register("Gold", () -> new Element(79, 117, -1, null, "Au", false));
    public static final RegistryObject<Element> Hg = ELEMENTS.register("Mercury", () -> new Element(80, 120, -1, null, "Hg", false));
    public static final RegistryObject<Element> Tl = ELEMENTS.register("Thallium", () -> new Element(81, 123, -1, null, "Tl", false));
    public static final RegistryObject<Element> Pb = ELEMENTS.register("Lead", () -> new Element(82, 125, -1, null, "Pb", false));
    public static final RegistryObject<Element> Bi = ELEMENTS.register("Bismuth", () -> new Element(83, 125, -1, null, "Bi", false));
    public static final RegistryObject<Element> Po = ELEMENTS.register("Polonium", () -> new Element(84, 124, -1, null, "Po", false));
    public static final RegistryObject<Element> At = ELEMENTS.register("Astatine", () -> new Element(85, 124, -1, null, "At", false));
    public static final RegistryObject<Element> Rn = ELEMENTS.register("Radon", () -> new Element(86, 134, -1, null, "Rn", false));
    public static final RegistryObject<Element> Fr = ELEMENTS.register("Francium", () -> new Element(87, 134, -1, null, "Fr", false));
    public static final RegistryObject<Element> Ra = ELEMENTS.register("Radium", () -> new Element(88, 136, -1, null, "Ra", false));
    public static final RegistryObject<Element> Ac = ELEMENTS.register("Actinium", () -> new Element(89, 136, -1, null, "Ac", false));
    public static final RegistryObject<Element> Th = ELEMENTS.register("Thorium", () -> new Element(90, 140, -1, null, "Th", false));
    public static final RegistryObject<Element> Pa = ELEMENTS.register("Protactinium", () -> new Element(91, 138, -1, null, "Pa", false));
    public static final RegistryObject<Element> U = ELEMENTS.register("Uranium", () -> new Element(92, 146, -1, null, "U", false));
    public static final RegistryObject<Element> U238 = ELEMENTS.register("Uranium-238", () -> new Element(92, 146, -1, null, "U-238", false));
    public static final RegistryObject<Element> U235 = ELEMENTS.register("Uranium-235", () -> new Element(92, 143, -1, null, "U-235", true));
    public static final RegistryObject<Element> Np = ELEMENTS.register("Neptunium", () -> new Element(93, 144, -1, null, "Np", false));
    public static final RegistryObject<Element> Pu = ELEMENTS.register("Plutonium", () -> new Element(94, 152, -1, null, "Pu", false));
    public static final RegistryObject<Element> Pu239 = ELEMENTS.register("Plutonium-239", () -> new Element(94, 145, -1, null, "Pu-239", false));
    public static final RegistryObject<Element> Pu241 = ELEMENTS.register("Plutonium-241", () -> new Element(94, 149, -1, null, "Pu-241", true));
    public static final RegistryObject<Element> Am = ELEMENTS.register("Americium", () -> new Element(95, 150, -1, null, "Am", false));
    public static final RegistryObject<Element> Cm = ELEMENTS.register("Curium", () -> new Element(96, 153, -1, null, "Cm", false));
    public static final RegistryObject<Element> Bk = ELEMENTS.register("Berkelium", () -> new Element(97, 152, -1, null, "Bk", false));
    public static final RegistryObject<Element> Cf = ELEMENTS.register("Californium", () -> new Element(98, 153, -1, null, "Cf", false));
    public static final RegistryObject<Element> Es = ELEMENTS.register("Einsteinium", () -> new Element(99, 153, -1, null, "Es", false));
    public static final RegistryObject<Element> Fm = ELEMENTS.register("Fermium", () -> new Element(100, 157, -1, null, "Fm", false));
    public static final RegistryObject<Element> Md = ELEMENTS.register("Mendelevium", () -> new Element(101, 157, -1, null, "Md", false));
    public static final RegistryObject<Element> No = ELEMENTS.register("Nobelium", () -> new Element(102, 157, -1, null, "No", false));
    public static final RegistryObject<Element> Lr = ELEMENTS.register("Lawrencium", () -> new Element(103, 159, -1, null, "Lr", false));
    public static final RegistryObject<Element> Rf = ELEMENTS.register("Rutherfordium", () -> new Element(104, 161, -1, null, "Rf", false));
    public static final RegistryObject<Element> Db = ELEMENTS.register("Dubnium", () -> new Element(105, 163, -1, null, "Db", false));
    public static final RegistryObject<Element> Sg = ELEMENTS.register("Seaborgium", () -> new Element(106, 165, -1, null, "Sg", false));
    public static final RegistryObject<Element> Bh = ELEMENTS.register("Bohrium", () -> new Element(107, 163, -1, null, "Bh", false));
    public static final RegistryObject<Element> Hs = ELEMENTS.register("Hassium", () -> new Element(108, 169, -1, null, "Hs", false));
    public static final RegistryObject<Element> Mt = ELEMENTS.register("Meitnerium", () -> new Element(109, 167, -1, null, "Mt", false));
    public static final RegistryObject<Element> Ds = ELEMENTS.register("Darmstadtium", () -> new Element(110, 171, -1, null, "Ds", false));
    public static final RegistryObject<Element> Rg = ELEMENTS.register("Roentgenium", () -> new Element(111, 169, -1, null, "Rg", false));
    public static final RegistryObject<Element> Cn = ELEMENTS.register("Copernicium", () -> new Element(112, 173, -1, null, "Cn", false));
    public static final RegistryObject<Element> Nh = ELEMENTS.register("Nihonium", () -> new Element(113, 171, -1, null, "Nh", false));
    public static final RegistryObject<Element> Fl = ELEMENTS.register("Flerovium", () -> new Element(114, 175, -1, null, "Fl", false));
    public static final RegistryObject<Element> Mc = ELEMENTS.register("Moscovium", () -> new Element(115, 173, -1, null, "Mc", false));
    public static final RegistryObject<Element> Lv = ELEMENTS.register("Livermorium", () -> new Element(116, 177, -1, null, "Lv", false));
    public static final RegistryObject<Element> Ts = ELEMENTS.register("Tennessine", () -> new Element(117, 177, -1, null, "Ts", false));
    public static final RegistryObject<Element> Og = ELEMENTS.register("Oganesson", () -> new Element(118, 176, -1, null, "Og", false));

    //fantasy todo Naquadah element names
    public static final RegistryObject<Element> Tr = ELEMENTS.register("Tritanium", () -> new Element(119, 178, -1, null, "Tr", false));
    public static final RegistryObject<Element> Dr = ELEMENTS.register("Duranium", () -> new Element(120, 180, -1, null, "Dr", false));
    public static final RegistryObject<Element> Ke = ELEMENTS.register("Trinium", () -> new Element(125, 198, -1, null, "Ke", false));
    public static final RegistryObject<Element> Nq = ELEMENTS.register("Naquadah", () -> new Element(174, 352, 140, null, "Nq", true));
    public static final RegistryObject<Element> Nq1 = ELEMENTS.register("NaquadahEnriched", () -> new Element(174, 354, 140, null, "Nq+", true));
    public static final RegistryObject<Element> Nq2 = ELEMENTS.register("Naquadria", () -> new Element(174, 348, 140, null, "*Nq*", true));
    public static final RegistryObject<Element> Nt = ELEMENTS.register("Neutronium", () -> new Element(0, 1000, -1, null, "Nt", false));
    public static final RegistryObject<Element> Sp = ELEMENTS.register("Space", () -> new Element(1, 0, -1, null, "Sp", false));
    public static final RegistryObject<Element> Ma = ELEMENTS.register("Magic", () -> new Element(1, 0, -1, null, "Ma", false));

}